const exportModules = {
  curry: require('./curry'),
  compose: require('./compose'),
  pipe: require('./pipe'),
  Identity: require('./identity'),
  Maybe: require('./maybe'),
  map: require('./map'),
  fold: require('./fold'),
  fold2: require('./fold2'),
  mjoin: require('./mjoin'),
  chain: require('./chain'),
  ap: require('./ap'),
  pass: require('./pass'),
  Either: require('./either'),
  Right: require('./either/right'),
  Left: require('./either/left'),
  fromNullable: require('./either/from-nullable'),
  tryCatch: require('./either/try-catch'),
  List: require('./list'),
  add: require('./add'),
  sub: require('./sub'),
  multiply: require('./multiply'),
  divide: require('./divide'),
  modulo: require('./modulo'),
  join: require('./join'),
  contains: require('./contains'),
  slice: require('./slice'),
  split: require('./split'),
  length: require('./length'),
  take: require('./take'),
  head: require('./head'),
  toUpperCase: require('./to-upper-case'),
  capitalize: require('./capitalize'),
  replace: require('./replace'),
}

exportModules.exposeGlobally = (ns = '$') =>
    globalThis[ns] = exportModules;

module.exports = exportModules;